[package]
name = "plumber"
version = "0.1.0"
authors = ["Maxi Saparov"]
keywords = ["pipe", "pipeline"]
categories = ["command-line-utilities"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
path = "src/main.rs"
name = "plumber"


[dependencies]
shlex = "1.2.0"
signal-hook = "0.3.17"
strum = { version = "0.25.0", features = ["strum_macros", "derive"] }
